version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api-supervisao:
    image: apelcgd/api-supervisao:latest
    container_name: ms-api-supervisao
    ports:
      - "${PORT_SERVER_APISUP}:5004"
    environment:
      - PORT_SERVER=${PORT_SERVER_APISUP}
      - MODO_DEV_PROD=${MODO_DEV_PROD}
      - ATIVA_SWAGGER_PROD=${ATIVA_SWAGGER_PROD}
      - ATIVA_LOGS=${ATIVA_LOGS}
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "${PORT}:5432"
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
